name: Setup Let's Encrypt SSL Certificate (acme.sh with Webroot)
description: "Automatically provision SSL certificates from Let's Encrypt using HTTP-01 webroot validation (no nginx restart needed)"

inputs:
  host:
    description: "VPS hostname or IP"
    required: true
  user:
    description: "SSH username"
    required: true
  port:
    description: "SSH port"
    required: false
    default: "22"
  domain:
    description: "Primary domain for the certificate (e.g., example.com)"
    required: true
  additional_domains:
    description: "Comma-separated list of additional domains (e.g., www.example.com,api.example.com)"
    required: false
    default: ""
  email:
    description: "Email for Let's Encrypt registration and renewal notices"
    required: true
  webroot_path:
    description: "Path on VPS where acme challenge files will be placed (default: /var/www/acme-challenges)"
    required: false
    default: "/var/www/acme-challenges"
  certificates_dir:
    description: "Directory to store certificates on VPS (default: /etc/letsencrypt)"
    required: false
    default: "/etc/letsencrypt"
  force_renewal:
    description: "Force certificate renewal even if valid (set to 'true' to renew)"
    required: false
    default: "false"

outputs:
  cert_path:
    description: "Path to the certificate file"
    value: "${{ steps.cert-paths.outputs.cert_path }}"
  key_path:
    description: "Path to the private key file"
    value: "${{ steps.cert-paths.outputs.key_path }}"
  cert_dir:
    description: "Directory containing certificates"
    value: "${{ steps.cert-paths.outputs.cert_dir }}"

runs:
  using: "composite"
  steps:
    - name: Provision SSL Certificate (acme.sh with Webroot)
      shell: bash
      env:
        DOMAIN: "${{ inputs.domain }}"
        ADDITIONAL_DOMAINS: "${{ inputs.additional_domains }}"
        EMAIL: "${{ inputs.email }}"
        CERT_DIR: "${{ inputs.certificates_dir }}"
        WEBROOT_PATH: "${{ inputs.webroot_path }}"
        FORCE_RENEWAL: "${{ inputs.force_renewal }}"
      run: |
        ssh -i ~/.ssh/id_rsa -p "${{ inputs.port }}" \
          -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o LogLevel=ERROR -T \
          "${{ inputs.user }}@${{ inputs.host }}" \
          "DOMAIN='$DOMAIN' ADDITIONAL_DOMAINS='$ADDITIONAL_DOMAINS' EMAIL='$EMAIL' CERT_DIR='$CERT_DIR' WEBROOT_PATH='$WEBROOT_PATH' FORCE_RENEWAL='$FORCE_RENEWAL' bash -s" <<-'EOF'
          set -euo pipefail

          echo "🔐 Provisioning SSL certificate with Let's Encrypt (acme.sh with Webroot)"
          echo "   Primary Domain: $DOMAIN"
          if [ -n "$ADDITIONAL_DOMAINS" ]; then
            echo "   Additional Domains: $ADDITIONAL_DOMAINS"
          fi
          echo "   Email: $EMAIL"
          echo "   Certificate Directory: $CERT_DIR"
          echo "   Webroot Path: $WEBROOT_PATH"

          # Validate inputs
          if [ -z "$DOMAIN" ] || [ -z "$EMAIL" ]; then
            echo "❌ Missing required parameters: domain and email are required"
            exit 1
          fi

          # Create certificate directory
          if [ ! -d "$CERT_DIR" ]; then
            echo "📁 Creating certificate directory: $CERT_DIR"
            sudo mkdir -p "$CERT_DIR"
          fi

          # Create webroot directory for acme challenges
          echo "📁 Creating webroot directory: $WEBROOT_PATH"
          sudo mkdir -p "$WEBROOT_PATH"
          sudo chmod 777 "$WEBROOT_PATH"  # Allow acme.sh user to write challenge files
          echo "✅ Webroot directory created with write permissions"

          # Install acme.sh if not already installed
          ACME_DIR="$HOME/.acme.sh"
          if [ ! -d "$ACME_DIR" ]; then
            echo "📥 Installing acme.sh..."
            curl https://get.acme.sh | sh -s email="$EMAIL" > /dev/null 2>&1

            # Source the acme.sh installation
            source "$HOME/.bashrc" 2>/dev/null || true

            if [ ! -d "$ACME_DIR" ]; then
              echo "❌ Failed to install acme.sh"
              exit 1
            fi
            echo "✅ acme.sh installed successfully"
          else
            echo "✅ acme.sh already installed"
          fi

          # Get acme.sh binary path
          ACME_BIN="$ACME_DIR/acme.sh"
          if [ ! -f "$ACME_BIN" ]; then
            echo "❌ acme.sh binary not found at $ACME_BIN"
            exit 1
          fi

          # Build domain list for acme.sh
          DOMAIN_ARGS="-d $DOMAIN"
          if [ -n "$ADDITIONAL_DOMAINS" ]; then
            # Convert comma-separated list to multiple -d flags
            IFS=',' read -ra DOMAINS <<< "$ADDITIONAL_DOMAINS"
            for dom in "${DOMAINS[@]}"; do
              dom=$(echo "$dom" | xargs)  # Trim whitespace
              if [ -n "$dom" ]; then
                DOMAIN_ARGS="$DOMAIN_ARGS -d $dom"
              fi
            done
          fi

          # Check for existing certificate
          CERT_PATH="$CERT_DIR/live/$DOMAIN/fullchain.pem"
          KEY_PATH="$CERT_DIR/live/$DOMAIN/privkey.pem"
          FORCE_FLAG=""

          if [ "$FORCE_RENEWAL" = "true" ]; then
            echo "🔄 Force renewal requested"
            FORCE_FLAG="--force"
          fi

          # Issue or renew certificate
          if [ -f "$CERT_PATH" ] && [ "$FORCE_RENEWAL" != "true" ]; then
            echo "ℹ️  Certificate already exists for $DOMAIN"
            echo "   Path: $CERT_PATH"
            echo "🔄 Attempting renewal if certificate is near expiration..."

            # acme.sh automatically handles renewal
            if $ACME_BIN --renew $FORCE_FLAG -d "$DOMAIN" 2>/dev/null || true; then
              echo "✅ Certificate renewal checked"
            fi
          else
            # Request new certificate using webroot HTTP-01 challenge
            echo "🚀 Requesting new certificate from Let's Encrypt..."
            echo "Setting up HTTP-01 validation (via webroot)..."
            ACME_LOG="$ACME_DIR/${DOMAIN}/${DOMAIN}.log"

            if $ACME_BIN --issue \
              $FORCE_FLAG \
              --webroot "$WEBROOT_PATH" \
              --server letsencrypt \
              $DOMAIN_ARGS 2>&1 | tee /tmp/acme_debug.log; then
              echo "✅ Certificate successfully provisioned"
            else
              echo "❌ Certificate provisioning failed"
              echo ""
              echo "=== acme.sh output ==="
              tail -50 /tmp/acme_debug.log || true
              echo "=== End acme.sh output ==="

              # Show acme.sh log if it exists
              if [ -f "$ACME_LOG" ]; then
                echo ""
                echo "=== acme.sh detailed log ==="
                tail -50 "$ACME_LOG" || true
                echo "=== End detailed log ==="
              fi

              # Troubleshooting suggestions
              echo ""
              echo "Troubleshooting:"
              echo "1. Verify nginx is configured to serve from $WEBROOT_PATH"
              echo "2. Check DNS resolution:"
              echo "   nslookup $DOMAIN"
              echo "3. Test webroot access:"
              echo "   curl -v http://$DOMAIN/.well-known/acme-challenge/test"
              echo "4. Check acme.sh log on VPS:"
              echo "   cat $ACME_LOG"

              exit 1
            fi
          fi

          # Install certificate to the target directory
          echo "📦 Installing certificate to $CERT_DIR..."
          LIVE_DIR="$CERT_DIR/live/$DOMAIN"
          if ! mkdir -p "$LIVE_DIR"; then
            echo "❌ Failed to create certificate directory"
            exit 1
          fi

          if ! $ACME_BIN --install-cert -d "$DOMAIN" \
            --key-file "$KEY_PATH" \
            --fullchain-file "$CERT_PATH" \
            --reloadcmd "echo 'Certificate installed'" 2>/dev/null; then
            echo "❌ Failed to install certificate"
            exit 1
          fi

          # Verify certificate exists
          if [ ! -f "$CERT_PATH" ] || [ ! -f "$KEY_PATH" ]; then
            echo "❌ Certificate files not found at expected paths"
            echo "   Expected cert: $CERT_PATH"
            echo "   Expected key: $KEY_PATH"
            exit 1
          fi

          # Set proper permissions
          sudo chown root:root "$CERT_PATH" "$KEY_PATH" 2>/dev/null || true
          sudo chmod 644 "$CERT_PATH" 2>/dev/null || true
          sudo chmod 600 "$KEY_PATH" 2>/dev/null || true

          # Display certificate details
          echo ""
          echo "✅ SSL Certificate Successfully Provisioned!"
          echo ""
          echo "📋 Certificate Details:"
          echo "   Cert Path: $CERT_PATH"
          echo "   Key Path: $KEY_PATH"

          # Show expiration date
          EXPIRY=$(openssl x509 -enddate -noout -in "$CERT_PATH" | cut -d= -f2)
          echo "   Expires: $EXPIRY"

          # Show all domains in certificate
          echo "   Domains in Certificate:"
          openssl x509 -noout -text -in "$CERT_PATH" | grep -A1 "Subject Alternative Name" | tail -1 | sed 's/DNS://g' | tr ',' '\n' | sed 's/^ */     - /' || true

          echo ""
          echo "🎉 Ready to use with nginx or other services!"
          echo "⏰ Auto-renewal enabled: certificates will renew automatically before expiration"
        EOF

    - name: Extract certificate paths
      id: cert-paths
      shell: bash
      run: |
        ssh -i ~/.ssh/id_rsa -p "${{ inputs.port }}" \
          -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o LogLevel=ERROR -T \
          "${{ inputs.user }}@${{ inputs.host }}" \
          "CERT_DIR='${{ inputs.certificates_dir }}' DOMAIN='${{ inputs.domain }}' bash -s" <<-'EOF'
          set -euo pipefail

          CERT_PATH="$CERT_DIR/live/$DOMAIN/fullchain.pem"
          KEY_PATH="$CERT_DIR/live/$DOMAIN/privkey.pem"
          CERT_LIVE_DIR="$CERT_DIR/live/$DOMAIN"

          if [ -f "$CERT_PATH" ] && [ -f "$KEY_PATH" ]; then
            echo "cert_path=$CERT_PATH" >> $GITHUB_OUTPUT
            echo "key_path=$KEY_PATH" >> $GITHUB_OUTPUT
            echo "cert_dir=$CERT_LIVE_DIR" >> $GITHUB_OUTPUT
            echo "✅ Paths exported for subsequent steps"
          else
            echo "❌ Certificate paths not found"
            exit 1
          fi
        EOF

    - name: Restart nginx Docker container (if needed)
      shell: bash
      run: |
        echo "✅ Certificate provisioning complete - no nginx restart needed!"
        echo "nginx continues serving from port 80 during validation"
