name: Check and install docker postgres image
description: "Check if PostgreSQL is installed in Docker, if not install it securely"

inputs:
  host:
    description: "VPS hostname or IP"
    required: true
  user:
    description: "SSH username"
    required: true
  port:
    description: "SSH port"
    required: false
    default: "22"
  postgres_admin_user: 
    description: "PostgreSQL admin username"
    required: true
  postgres_admin_pass:
    description: "PostgreSQL admin password"
    required: true
  postgres_port:
    description: "Public port for PostgreSQL"
    type: number
    required: true
    default: 5432

runs:
  using: "composite"
  steps:
    - name: Check & Install PostgreSQL in Docker (Secure)
      env:
        POSTGRES_ADMIN_USER: ${{ inputs.postgres_admin_user }}
        POSTGRES_ADMIN_PASS: ${{ inputs.postgres_admin_pass }}
        POSTGRES_PORT: ${{ inputs.postgres_port }}
      shell: bash
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ inputs.user }}@${{ inputs.host }} \
            bash -s -- \
            "${{ inputs.postgres_admin_user }}" \
            "${{ inputs.postgres_admin_pass }}" << 'EOF'

            POSTGRES_ADMIN_USER=$1
            POSTGRES_ADMIN_PASS=$2

            echo "🔎 Checking PostgreSQL in Docker..."

            if ! sudo docker ps --format '{{.Names}}' | grep -q postgres_container; then
              echo "❌ PostgreSQL is not running. Installing..."
              sudo docker pull postgres:latest
              sudo docker run -d \
                --name postgres_container \
                -e POSTGRES_USER=$POSTGRES_ADMIN_USER \
                -e POSTGRES_PASSWORD=$POSTGRES_ADMIN_PASS \
                -e POSTGRES_DB=postgres \
                -p 5432:5432 \
                -v postgres_data:/var/lib/postgresql/data \
                --restart always \
                postgres:latest
              echo "✅ PostgreSQL installed and running with admin user only!"
            else
              echo "✅ PostgreSQL is already running!"
            fi

            sudo ufw allow 5432/tcp
            echo "✅ Port 5432 is open for PostgreSQL!"
          EOF

    - name: Check PostgreSQL Connection
      shell: bash
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ inputs.user }}@${{ inputs.host }} \
          bash -s -- "${{ inputs.postgres_admin_user }}" << 'EOF'

          POSTGRES_ADMIN_USER=$1
          echo "⏳ Checking PostgreSQL connection..."
          MAX_RETRIES=10
          RETRY_INTERVAL=2
          COUNT=0
          until sudo docker exec postgres_container pg_isready -U "$POSTGRES_ADMIN_USER" || [ $COUNT -eq $MAX_RETRIES ]; do
            echo "🔄 Waiting for PostgreSQL to be ready... ($COUNT/$MAX_RETRIES)"
            sleep $RETRY_INTERVAL
            COUNT=$((COUNT+1))
          done
          if [ $COUNT -eq $MAX_RETRIES ]; then
            echo "❌ PostgreSQL did not become ready in time. Exiting..."
            exit 1
          fi
          echo "✅ PostgreSQL is ready and accepting connections!"
        EOF