# actions/ssh-setup/action.yml
name: SSH Setup & Connect (Ubuntu)
description: Write SSH key, add host to known_hosts, and connect to VPS
inputs:
  host:
    description: VPS hostname or IP
    required: true
  user:
    description: SSH username
    required: true
  private_key:
    description: OpenSSH private key contents
    required: true
  port:
    description: SSH port
    required: false
    default: "22"
  strict_host_key_checking:
    description: yes|no (matches your original: no)
    required: false
    default: "no"

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        [ -n "${{ inputs.host }}" ] || { echo "❌ inputs.host is empty"; exit 1; }
        [ -n "${{ inputs.user }}" ] || { echo "❌ inputs.user is empty"; exit 1; }
        [ -n "${{ inputs.private_key }}" ] || { echo "❌ inputs.private_key is empty"; exit 1; }

    - name: Setup SSH Key 🔑
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
        # Preserve newlines; strip CR if pasted from Windows
        printf '%s' "${{ inputs.private_key }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H -p "${{ inputs.port }}" "${{ inputs.host }}" >> ~/.ssh/known_hosts

    - name: Connect to VPS ✅
      shell: bash
      run: |
        set -euo pipefail
        ssh -i ~/.ssh/id_rsa -p "${{ inputs.port }}" \
          -o StrictHostKeyChecking=${{ inputs.strict_host_key_checking }} \
          -o IdentitiesOnly=yes \
          "${{ inputs.user }}@${{ inputs.host }}" \
          "echo Connected to VPS: \$(hostname)"
