# actions/ssh-setup/action.yml
name: Setup SSH key & Connect (Ubuntu)
description: "Write SSH key, add host to known_hosts, and connect to VPS"

inputs:
  host:
    description: "VPS hostname or IP"
    required: true
  user:
    description: "SSH username"
    required: true
  private_key:
    description: "OpenSSH private key contents"
    required: true
  port:
    description: "SSH port"
    required: false
    default: "22"
  strict_host_key_checking:
    description: "yes|no"
    required: false
    default: "no"

runs:
  using: "composite"
  steps:
    - name: Setup SSH Key
      shell: bash
      run: |
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
        printf '%s' "${{ inputs.private_key }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Silence ssh-keyscan banner lines (stderr) to avoid red text
        ssh-keyscan -H -p "${{ inputs.port }}" "${{ inputs.host }}" 2>/dev/null >> ~/.ssh/known_hosts

    - name: Connect to VPS
      shell: bash
      run: |
        ssh -i ~/.ssh/id_rsa -p "${{ inputs.port }}" \
          -o StrictHostKeyChecking=${{ inputs.strict_host_key_checking }} \
          -o IdentitiesOnly=yes \
          -o LogLevel=ERROR \
          "${{ inputs.user }}@${{ inputs.host }}" \
          "echo Connected to VPS: \$(hostname)"
